/*
 * rules_db.h — 规则数据库
 *
 * 100+ 条高频 NL 命令规则。每条规则：关键词模式 → intent + template_id。
 * 格式：{keywords, intent, template_id, slot_names}
 *
 * 匹配算法：对输入分词 → 对每条规则检查所有 keywords 是否都在输入中
 *          → 如果命中 → 提取命名槽位（<name> 格式）
 */

#ifndef NL_RULES_DB_H
#define NL_RULES_DB_H

#include "rule_engine.h"
#include <stddef.h>

/* 规则槽位描述 */
typedef struct {
    const char *name;       /* 槽位名 */
    const char *match_type; /* "word"(下一个词), "after_key"(关键词后的内容), "quoted"(引号内) */
    const char *key;        /* 触发关键词（match_type=after_key 时使用） */
} NlRuleSlotDef;

/* 单条规则 */
typedef struct {
    int           id;
    NlIntentType  intent;
    int           template_id;
    const char   *keywords[8];  /* 必须同时出现的关键词（NULL 结尾） */
    NlRuleSlotDef slots[6];     /* 槽位提取定义 */
    const char   *example;      /* 示例输入 */
} NlRule;

/* ============================================================
 * 规则表（按 intent 分组）
 * ============================================================ */

static const NlRule RULES[] = {

    /* ── create_dir · 创建目录 ── */
    {1,  NL_INTENT_CREATE_DIR, 1,
     {"创建", "文件夹", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建一个叫 test 的文件夹"},
    {2,  NL_INTENT_CREATE_DIR, 1,
     {"创建", "目录", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建一个叫 build 的目录"},
    {3,  NL_INTENT_CREATE_DIR, 1,
     {"新建", "文件夹", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "新建一个叫 logs 的文件夹"},
    {4,  NL_INTENT_CREATE_DIR, 1,
     {"新建", "目录", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "新建一个叫 src 的目录"},
    {5,  NL_INTENT_CREATE_DIR, 1,
     {"mkdir", NULL},
     {{"name", "word", NULL}, {NULL}},
     "mkdir test"},
    {6,  NL_INTENT_CREATE_DIR, 1,
     {"建立", "目录", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "建立一个叫 data 的目录"},
    {7,  NL_INTENT_CREATE_DIR, 1,
     {"创建", "个", "文件夹", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建个叫 temp 的文件夹"},
    {8,  NL_INTENT_CREATE_DIR, 1,
     {"创建", "个", "目录", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建个叫 backup 的目录"},

    /* ── create_file · 创建文件 ── */
    {10, NL_INTENT_CREATE_FILE, 2,
     {"创建", "文件", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建一个叫 README.md 的文件"},
    {11, NL_INTENT_CREATE_FILE, 2,
     {"新建", "文件", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "新建一个叫 main.c 的文件"},
    {12, NL_INTENT_CREATE_FILE, 2,
     {"touch", NULL},
     {{"name", "word", NULL}, {NULL}},
     "touch config.json"},
    {13, NL_INTENT_CREATE_FILE, 2,
     {"创建", "空文件", NULL},
     {{"name", "after_key", "叫"}, {NULL}},
     "创建空文件叫 .env"},
    {14, NL_INTENT_CREATE_FILE, 2,
     {"写入", "文件", NULL},
     {{"name", "after_key", "到"}, {NULL}},
     "写入 hello 到 test.txt"},

    /* ── delete · 删除 ── */
    {20, NL_INTENT_DELETE, 3,
     {"删除", NULL},
     {{"target", "after_key", "删除"}, {NULL}},
     "删除 test 目录"},
    {21, NL_INTENT_DELETE, 3,
     {"删掉", NULL},
     {{"target", "after_key", "删掉"}, {NULL}},
     "删掉 /tmp/test"},
    {22, NL_INTENT_DELETE, 3,
     {"rm", NULL},
     {{"target", "word", NULL}, {NULL}},
     "rm file.txt"},
    {23, NL_INTENT_DELETE, 3,
     {"移除", NULL},
     {{"target", "after_key", "移除"}, {NULL}},
     "移除 build 目录"},
    {24, NL_INTENT_DELETE, 3,
     {"清理", NULL},
     {{"target", "after_key", "清理"}, {NULL}},
     "清理 /tmp 目录"},
    {25, NL_INTENT_DELETE, 3,
     {"清除", NULL},
     {{"target", "after_key", "清除"}, {NULL}},
     "清除缓存文件"},

    /* ── move · 移动/重命名 ── */
    {30, NL_INTENT_MOVE, 4,
     {"移动", NULL},
     {{"source", "after_key", "移动"}, {"dest", "after_key", "到"}, {NULL}},
     "移动 file.txt 到 /tmp"},
    {31, NL_INTENT_MOVE, 4,
     {"mv", NULL},
     {{"source", "word", NULL}, {"dest", "word", NULL}, {NULL}},
     "mv old.txt new.txt"},
    {32, NL_INTENT_MOVE, 4,
     {"重命名", NULL},
     {{"source", "after_key", "重命名"}, {"dest", "after_key", "为"}, {NULL}},
     "重命名 old.txt 为 new.txt"},
    {33, NL_INTENT_MOVE, 4,
     {"改名", NULL},
     {{"source", "after_key", "改名"}, {"dest", "after_key", "为"}, {NULL}},
     "改名 config.json 为 config.bak"},

    /* ── copy · 复制 ── */
    {40, NL_INTENT_COPY, 5,
     {"复制", NULL},
     {{"source", "after_key", "复制"}, {"dest", "after_key", "到"}, {NULL}},
     "复制 file.txt 到 /backup"},
    {41, NL_INTENT_COPY, 5,
     {"拷贝", NULL},
     {{"source", "after_key", "拷贝"}, {"dest", "after_key", "到"}, {NULL}},
     "拷贝 src/ 到 /tmp"},
    {42, NL_INTENT_COPY, 5,
     {"cp", NULL},
     {{"source", "word", NULL}, {"dest", "word", NULL}, {NULL}},
     "cp a.txt b.txt"},
    {43, NL_INTENT_COPY, 5,
     {"备份", NULL},
     {{"source", "after_key", "备份"}, {NULL}},
     "备份 config.json"},

    /* ── list_dir · 列出目录 ── */
    {50, NL_INTENT_LIST_DIR, 6,
     {"列出", "文件", NULL},
     {{"location", "after_key", "列出"}, {NULL}},
     "列出当前目录的文件"},
    {51, NL_INTENT_LIST_DIR, 6,
     {"列出", "目录", NULL},
     {{"location", "after_key", "列出"}, {NULL}},
     "列出 /tmp 目录的内容"},
    {52, NL_INTENT_LIST_DIR, 6,
     {"显示", "文件", "列表", NULL},
     {{"location", "after_key", "显示"}, {NULL}},
     "显示当前目录的文件列表"},
    {53, NL_INTENT_LIST_DIR, 6,
     {"ls", NULL},
     {{NULL}},
     "ls"},
    {54, NL_INTENT_LIST_DIR, 6,
     {"看看", "目录", NULL},
     {{"location", "after_key", "看看"}, {NULL}},
     "看看当前目录"},
    {55, NL_INTENT_LIST_DIR, 6,
     {"显示", "所有文件", NULL},
     {{NULL}},
     "显示所有文件"},
    {56, NL_INTENT_LIST_DIR, 6,
     {"列出", "文件夹", NULL},
     {{NULL}},
     "列出文件夹"},
    {57, NL_INTENT_LIST_DIR, 6,
     {"显示", "目录结构", NULL},
     {{NULL}},
     "显示目录结构"},

    /* ── view_file · 查看文件 ── */
    {60, NL_INTENT_VIEW_FILE, 7,
     {"查看", "文件", NULL},
     {{"target", "after_key", "查看"}, {NULL}},
     "查看 README.md 文件"},
    {61, NL_INTENT_VIEW_FILE, 7,
     {"显示", "内容", NULL},
     {{"target", "after_key", "显示"}, {NULL}},
     "显示 config.json 的内容"},
    {62, NL_INTENT_VIEW_FILE, 7,
     {"cat", NULL},
     {{"target", "word", NULL}, {NULL}},
     "cat /etc/hosts"},
    {63, NL_INTENT_VIEW_FILE, 7,
     {"打开", "文件", NULL},
     {{"target", "after_key", "打开"}, {NULL}},
     "打开 test.txt 文件"},
    {64, NL_INTENT_VIEW_FILE, 7,
     {"看看", "内容", NULL},
     {{"target", "after_key", "看看"}, {NULL}},
     "看看 error.log 的内容"},

    /* ── find_files · 查找文件 ── */
    {70, NL_INTENT_FIND_FILES, 8,
     {"查找", "文件", NULL},
     {{"pattern", "after_key", "查找"}, {NULL}},
     "查找所有 python 文件"},
    {71, NL_INTENT_FIND_FILES, 8,
     {"搜索", "文件", NULL},
     {{"pattern", "after_key", "搜索"}, {NULL}},
     "搜索所有 .log 文件"},
    {72, NL_INTENT_FIND_FILES, 8,
     {"find", NULL},
     {{"pattern", "word", NULL}, {NULL}},
     "find *.c"},
    {73, NL_INTENT_FIND_FILES, 8,
     {"找", "文件", NULL},
     {{"pattern", "after_key", "找"}, {NULL}},
     "找所有大于 100M 的文件"},
    {74, NL_INTENT_FIND_FILES, 8,
     {"找到", NULL},
     {{"pattern", "after_key", "找到"}, {NULL}},
     "找到所有 python 文件"},

    /* ── change_dir · 切换目录 ── */
    {80, NL_INTENT_CHANGE_DIR, 9,
     {"进入", "目录", NULL},
     {{"location", "after_key", "进入"}, {NULL}},
     "进入 /home/user 目录"},
    {81, NL_INTENT_CHANGE_DIR, 9,
     {"进入", "文件夹", NULL},
     {{"location", "after_key", "进入"}, {NULL}},
     "进入 src 文件夹"},
    {82, NL_INTENT_CHANGE_DIR, 9,
     {"cd", NULL},
     {{"location", "word", NULL}, {NULL}},
     "cd /tmp"},
    {83, NL_INTENT_CHANGE_DIR, 9,
     {"切换", "目录", NULL},
     {{"location", "after_key", "到"}, {NULL}},
     "切换到上级目录"},
    {84, NL_INTENT_CHANGE_DIR, 9,
     {"切换到", NULL},
     {{"location", "after_key", "切换到"}, {NULL}},
     "切换到 /var/log"},
    {85, NL_INTENT_CHANGE_DIR, 9,
     {"回到", NULL},
     {{"location", "word", NULL}, {NULL}},
     "回到上级目录"},
    {86, NL_INTENT_CHANGE_DIR, 9,
     {"返回", NULL},
     {{NULL}},
     "返回上级目录"},

    /* ── show_process · 进程查看 ── */
    {90, NL_INTENT_SHOW_PROCESS, 10,
     {"显示", "进程", NULL},
     {{NULL}},
     "显示所有进程"},
    {91, NL_INTENT_SHOW_PROCESS, 10,
     {"查看", "进程", NULL},
     {{NULL}},
     "查看进程列表"},
    {92, NL_INTENT_SHOW_PROCESS, 10,
     {"ps", NULL},
     {{NULL}},
     "ps"},
    {93, NL_INTENT_SHOW_PROCESS, 10,
     {"显示", "占用", "内存", NULL},
     {{NULL}},
     "显示占用内存最多的进程"},
    {94, NL_INTENT_SHOW_PROCESS, 10,
     {"显示", "CPU", "进程", NULL},
     {{NULL}},
     "显示 CPU 占用最高的进程"},
    {95, NL_INTENT_SHOW_PROCESS, 10,
     {"系统", "负载", NULL},
     {{NULL}},
     "查看系统负载"},
    {96, NL_INTENT_SHOW_PROCESS, 10,
     {"top", NULL},
     {{NULL}},
     "top"},
    {97, NL_INTENT_SHOW_PROCESS, 10,
     {"系统", "资源", NULL},
     {{NULL}},
     "查看系统资源使用情况"},
    {98, NL_INTENT_SHOW_PROCESS, 10,
     {"运行", "程序", NULL},
     {{NULL}},
     "显示正在运行的程序"},

    /* ── search_content · 搜索内容 ── */
    {100, NL_INTENT_SEARCH_CONTENT, 11,
     {"grep", NULL},
     {{"pattern", "word", NULL}, {"location", "word", NULL}, {NULL}},
     "grep error *.log"},
    {101, NL_INTENT_SEARCH_CONTENT, 11,
     {"搜索", "内容", NULL},
     {{"pattern", "after_key", "搜索"}, {NULL}},
     "搜索包含 error 的内容"},
    {102, NL_INTENT_SEARCH_CONTENT, 11,
     {"查找", "包含", NULL},
     {{"pattern", "after_key", "包含"}, {NULL}},
     "查找包含 TODO 的文件"},
    {103, NL_INTENT_SEARCH_CONTENT, 11,
     {"找出", "包含", NULL},
     {{"pattern", "after_key", "包含"}, {NULL}},
     "找出包含 password 的文件"},
    {104, NL_INTENT_SEARCH_CONTENT, 11,
     {"搜索", "代码", NULL},
     {{"pattern", "after_key", "搜索"}, {NULL}},
     "搜索代码中的 main 函数"},

    /* ── run_cmd · 执行命令 ── */
    {110, NL_INTENT_RUN_CMD, 12,
     {"运行", NULL},
     {{"command", "after_key", "运行"}, {NULL}},
     "运行 make"},
    {111, NL_INTENT_RUN_CMD, 12,
     {"执行", NULL},
     {{"command", "after_key", "执行"}, {NULL}},
     "执行 ./configure"},
    {112, NL_INTENT_RUN_CMD, 12,
     {"编译", "项目", NULL},
     {{NULL}},
     "编译项目"},
    {113, NL_INTENT_RUN_CMD, 12,
     {"构建", NULL},
     {{NULL}},
     "构建项目"},
    {114, NL_INTENT_RUN_CMD, 12,
     {"make", NULL},
     {{NULL}},
     "make"},
    {115, NL_INTENT_RUN_CMD, 12,
     {"安装", "包", NULL},
     {{NULL}},
     "安装依赖包"},
    {116, NL_INTENT_RUN_CMD, 12,
     {"重启", "服务", NULL},
     {{NULL}},
     "重启 nginx 服务"},
    {117, NL_INTENT_RUN_CMD, 12,
     {"启动", "服务", NULL},
     {{NULL}},
     "启动数据库服务"},

    /* ── other · 常用操作 ── */
    {120, NL_INTENT_OTHER, 0,
     {"帮助", NULL},
     {{NULL}},
     "帮助"},
    {121, NL_INTENT_OTHER, 0,
     {"help", NULL},
     {{NULL}},
     "help"},
    {122, NL_INTENT_OTHER, 0,
     {"怎么", NULL},
     {{NULL}},
     "怎么用"},
    {123, NL_INTENT_CHANGE_DIR, 9,
     {"上级", "目录", NULL},
     {{NULL}},
     "上级目录"},
    {124, NL_INTENT_LIST_DIR, 6,
     {"显示", "目录", "内容", NULL},
     {{"location", "after_key", "显示"}, {NULL}},
     "显示 /tmp 目录的内容"},
    /* 末尾标记 */
    {0, 0, 0, {NULL}, {{NULL}}, NULL}
};

/* 规则总数（不含末尾标记） */
static const int RULE_COUNT = sizeof(RULES) / sizeof(RULES[0]) - 1;

#endif /* NL_RULES_DB_H */
